Add typed-protocols-doc
input-output-hk/typed-protocols pull request #46
Opened 2023-11-30 15:33 UTC by tdammers

This adds a subproject that uses Template Haskell to generate HTML documentation from a typed protocol definition.

2024-01-25 15:12 UTC, coot commented on typed-protocols-doc/LICENSE
> +                        http://www.apache.org/licenses/
Could you also copy the `../typed-protocols/NOTICE` file (& please mention it in `extra-doc-files`).

2024-01-25 15:12 UTC, coot commented on typed-protocols-doc/typed-protocols-doc.cabal
> +copyright:          2023 IO Global
```suggestion
copyright:          2023 Input Output Global Inc (IOG), 2023-2024 Intersect
```

2024-01-25 15:12 UTC, coot commented on typed-protocols-doc/typed-protocols-doc.cabal
> +-- extra-doc-files:    CHANGELOG.md
```suggestion
extra-doc-files:    CHANGELOG.md
```

2024-01-25 15:12 UTC, coot commented on typed-protocols-doc/typed-protocols-doc.cabal
> +    ghc-options: -Wall
For libraries (but not for tests or demos) we tend to use more warnings; consider if the are beneficial here too:
```
  ghc-options:       -Wall
                     -Wno-unticked-promoted-constructors
                     -Wcompat
                     -Wincomplete-uni-patterns
                     -Wincomplete-record-updates
                     -Wpartial-fields
                     -Widentities
                     -Wredundant-constraints

```

2024-01-25 15:12 UTC, coot commented on cabal.project
> +  subdir: serdoc-core
is there a chance to get this published to `CHaP` or even better `hackage`? This year I'd like to publish `typed-protocols` to `hackage`, but we don't need to publish everything at once.

2024-01-25 15:12 UTC, coot commented on typed-protocols-doc/src/Network/TypedProtocol/Documentation/TestProtocol.hs
> +module Network.TypedProtocol.Documentation.TestProtocol
Should this be placed in `typed-protocols-docs/test` folder?
Or if you want you could also add it to `typed-protocols-examples`.

2024-01-25 15:12 UTC, coot commented on typed-protocols-doc/test/Network/TypedProtocol/Tests/ControlProtocol.hs
> +{-# LANGUAGE DataKinds #-}
Is this the `kes` agent protocol, or just a variant for testing?

2024-01-25 15:14 UTC, coot commented
We should build `typed-protocols-docs` in `GHA`, e.g. `.github/workflows/haskell.yml`.

2024-01-30 11:56 UTC, tdammers commented on cabal.project
> +  subdir: serdoc-core
Would love to, yes.

2024-01-30 12:07 UTC, tdammers commented on typed-protocols-doc/test/Network/TypedProtocol/Tests/ControlProtocol.hs
> +{-# LANGUAGE DataKinds #-}
It's an older version of one of the KES agent protocols, used here for testing. It was easier to just use this one than to come up with a made-up protocol that covers the same use cases.

2024-02-01 10:03 UTC, coot requested changes

2024-02-01 10:03 UTC, coot commented on typed-protocols-doc/NOTICE
> +Copyright 2019-2021 Input Output (Hong Kong) Ltd.
```suggestion
Copyright 2019-2024 Input Output Global Inc (IOG)
```

2024-02-01 10:03 UTC, coot commented on typed-protocols-doc/typed-protocols-doc.cabal
> +copyright:          2023 Input Output Global Inc (IOG), 2023-2024 Intersect
```suggestion
copyright:          2023-2024 Input Output Global Inc (IOG)
```
sorry my mistake, we shouldn't  use `Intersect` as this repo will not be transferred to `IntersectMBO`.

2024-02-01 15:39 UTC, tdammers commented on typed-protocols-doc/typed-protocols-doc.cabal
> +copyright:          2023 Input Output Global Inc (IOG), 2023-2024 Intersect
No problem.

2024-02-02 14:37 UTC, tdammers commented
I've added typed-protocols-doc to the GHA workflow, and it's currently passing.

2024-02-12 12:55 UTC, coot approved these changes
LGTM

2024-02-12 13:14 UTC, merged