New API for typed-protocols
input-output-hk/typed-protocols pull request #52
Opened 2024-08-20 14:00 UTC by coot

Takes lessons learned in #3, but preserving original (parallel) pipelining design.

The original pipelining is limited to transitions which can be fulfilled by remote transitions, this could be lifted by the more general scheme of tracking pipelined transition at type level done in #3 in the future.  But what's important we run the receiver for pipelined transition in parallel, which preserves performance. Below is the comparison of plain and modified `cardano-node-9.1.0` syncing mainet:

![block-acc-size-9 1 0](https://github.com/user-attachments/assets/56154e77-672f-4b3f-80a3-225746a5eccb)

2024-08-22 19:10 UTC, coot commented
I removed `typed-protocols-doc` from GHA for now, since it doesn't build against `typed-protocols-0.2.0.0`.

2024-08-26 14:51 UTC, bolt12 commented on typed-protocols-examples/src/Network/TypedProtocol/Driver/Simple.hs
> +    runPeerWithDriver driver peer Nothing
want to do: https://github.com/IntersectMBO/ouroboros-network/issues/594 here?

2024-09-03 13:13 UTC, coot commented on typed-protocols-examples/src/Network/TypedProtocol/Driver/Simple.hs
> +    runPeerWithDriver driver peer Nothing
This is in `typed-protocols-examples`, it doesn't matter than match, does it?

2024-09-03 13:15 UTC, coot commented on typed-protocols-examples/src/Network/TypedProtocol/Driver/Simple.hs
> +    runPeerWithDriver driver peer Nothing
In `typed-protocols` we anyway need `io-classes` dependency for `Monad{STM,Async}` to implement `runPipelinedPeerWithDriver`.

2024-09-03 13:38 UTC, coot commented on typed-protocols-examples/src/Network/TypedProtocol/Driver/Simple.hs
> +    runPeerWithDriver driver peer Nothing
Looking more closely, this will require to annotate `Driver` with a `failure` type, which `runPeer` will return, so it will be quite substantial change.

I'd leave it for later, when we also include implementation of `Driver.Simple` and `Driver.WithLimits` in `typed-protocols`.  This way we wouldn't pull a dependency on a logging framework - error handling will be up to the user.

2024-09-16 10:00 UTC, bolt12 requested changes
Very clean! I looked through most of it except tests which I only skimmed, the API looks much more polished! :) I just made a some comments, which don't impact the design at all.

2024-09-16 10:00 UTC, bolt12 commented on typed-protocols/src/Network/TypedProtocol/Core.hs
> +-- * whe protocol itself, which is also expected to be the kind of the types
```suggestion
-- * the protocol itself, which is also expected to be the kind of the types
```

2024-09-16 10:00 UTC, bolt12 commented on typed-protocols/src/Network/TypedProtocol/Lemmas.hs
> +  SingAsServer ReflServerAgency x        = case x of {}
This is the proof that proofs that typed-protocol guarantees the protocols to be deadlock free. I'd add a nice note about that 😄

2024-09-16 10:00 UTC, bolt12 commented on typed-protocols/src/Network/TypedProtocol/Lemmas.hs
> +  SingAsServer ReflServerAgency x        = case x of {}
Is it possible to also add a comment with a more readable spec? I find the uses of relative hard to read.

2024-09-16 10:00 UTC, bolt12 commented on typed-protocols/src/Network/TypedProtocol/Lemmas.hs
> +--
Same here:
```
forall (pr :: PeerRole) (a :: Agency) (ra :: RelativeAgency).
       ra == Relative pr a ->
       NobodyHasAgency == Relative (FlipAgency pr) a ->
       Relative pr a == NobodyHasAgency && Relative (FlipAgency pr) a == NobodyHasAgency
```

2024-09-16 10:00 UTC, bolt12 commented on typed-protocols/src/Network/TypedProtocol/Lemmas.hs
> +  SingAsServer ReflServerAgency x        = case x of {}
for example: 

```
forall (pr :: PeerRole) (a :: Agency) (ra :: RelativeAgency).
       ra == Relative pr a ->
       ra == Relative (FlipAgency pr) a ->
       Relative pr a == NobodyHasAgency && Relative (FlipAgency pr) a == NobodyHasAgency
```

Bonus points if we could make the syntax closer to this which is much more readable and easier. For what is worth I had to go back and forth between definitions to know which is which since the names are so similar.

2024-09-16 10:00 UTC, bolt12 commented on typed-protocols/src/Network/TypedProtocol/Lemmas.hs
> +                                          (Relative             pr  a)
Is this proof really needed? Isn't `ReflNobodyHasAgency a b` commutative?

2024-09-16 10:00 UTC, bolt12 commented on typed-protocols-stateful/src/Data/Type/Queue.hs
> +                   -> SingQueueF f q
`Why do you need SomeF ?` can't you "monomorphise" it to `f st st'` since it is what is going to be used for? This would avoid `unsafeCoerce` usage

2024-09-16 10:00 UTC, bolt12 commented on typed-protocols-stateful/src/Data/Type/Queue.hs
> +
I'd like to see more explanations/motivations for some of the constructs since some of them it is hard to see right away why do you need them

2024-09-16 12:31 UTC, coot commented on typed-protocols/src/Network/TypedProtocol/Lemmas.hs
> +  SingAsServer ReflServerAgency x        = case x of {}
I don't think this is possible, the output of `Relative` is a type level thing, so one cannot apply `==` to it.

2024-09-16 12:34 UTC, coot commented on typed-protocols/src/Network/TypedProtocol/Lemmas.hs
> +                                          (Relative             pr  a)
I think so, note that the assumptions are different.

2024-09-16 12:36 UTC, coot commented on typed-protocols-stateful/src/Data/Type/Queue.hs
> +                   -> SingQueueF f q
This whole module is not needed.  It's an artifact of the previous approach.

2024-09-16 12:38 UTC, bolt12 commented on typed-protocols/src/Network/TypedProtocol/Lemmas.hs
> +  SingAsServer ReflServerAgency x        = case x of {}
I don't mean applying ==, I mean having a comment with a prettier version that's easier and more straightforward to read. It can be pseudo syntax

2024-09-16 12:41 UTC, coot commented on typed-protocols-stateful/src/Data/Type/Queue.hs
> +
As above :grin:

2024-09-16 13:11 UTC, coot commented on typed-protocols/src/Network/TypedProtocol/Lemmas.hs
> +  SingAsServer ReflServerAgency x        = case x of {}
I added haddocks which I hope are helpful to decipher the lemma.

2024-09-16 13:24 UTC, coot commented
^ I rebased on top of  recent `main` branch (which requires some rather simple conflict resultion).

2024-09-16 13:59 UTC, bolt12 commented on typed-protocols-stateful/src/Data/Type/Queue.hs
> +                   -> SingQueueF f q
Why dont we remove it then?

2024-09-16 14:11 UTC, bolt12 approved these changes

2024-09-16 14:31 UTC, coot commented on typed-protocols-stateful/src/Data/Type/Queue.hs
> +                   -> SingQueueF f q
That's what I did :smile:

2024-09-16 15:15 UTC, merged